language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: sUdAQbsqk/cJet8SOUL/Lc5/cec9RHVbQuCMAr8L4INFGnNFLeTxDTgIjNRtOIIqGya2smGPaEitA569cWgXCFSLimxRkA47jYkHRvfVScmEXkA1ncPUzg4cpI+tABD7Uzs5F4GdofJ7tJ6xgOQksXCD3CvsNMUW6ZfzxWqD19pfbJMwn8aI5gxB6Gry0rs9syvu0NcXLThHBdrciEInAzVWBzbZ9T011nFAc8GLjdOQ5GstWfNq2bdk8xJNctvfIts7DH53wDoJQ2CorkztuWQl67hby6P6G7nfokwUb00//IkR3V2SVnO7Y1iCb+05310DBeBDG4gt6u5Z/IaBUMt/pOKPJ9liKEKX9TjzBJ7iTNe7NdI7XV9v2yoPKR5q3mgWnK2PdvfESS53MacbMEqNwdOIRt72KoNfAsGRNNr7e+enPF0Er3NeWRFmfUYZt8VqWcm1eTxq8SYNbRoBJonqE9Migee2s0dgGSuSR3jfszO+b8RjAreipxbNQOBOOvTkvHzRiOA0TWuJG7qGicJ16dLIGTD5Nm6hi4aRHwdw3b/CHtbeX8jBLfWOg7q6avgax3gJjUqff9ztkQGC9iinTL6MsigVo5/tKBiDPvUy6CAdHEIWSl+qB1FFyQVXEzJyhNuMJVHvkqKFId81L8Zpa84H0d86xuntm1CU05s=
  app: mitrainingplaner
  on:
    repo: nokia-wroclaw/innovativeproject-training-planner
    branch: travis-test
script:
- echo "skipping tests "
